osx_image: xcode8
language: objective-c
branches:
  only:
  - master
  - develop
  - /^feature\/\w+/
env:
  global:
  - BUILD_NUM=$TRAVIS_BUILD_NUMBER
  - PROJECT_REPO_SLUG=$TRAVIS_REPO_SLUG
  - GIT_BRANCH=$TRAVIS_BRANCH
  matrix:
  - PLATFORM=web
  - PLATFORM=android
  - PLATFORM=ios
before_install:
- rvm use 2.3.1
- nvm install 6.9.2
- brew update || brew update
- brew install git-lfs && git-lfs install && git-lfs pull
- git clone 'https://github.com/fathens/fastlane-ionic.git#develop' fastlane
- sudo easy_install pip && sudo pip install awscli
- aws s3 cp s3://${AWS_S3_BUCKET}/${PROJECT_REPO_SLUG}/persistent.tar.bz2 - | tar jxf -
install:
- gem install fastlane --no-document
- (npm install || npm install) && npm install -g ionic cordova
- test "$PLATFORM" != "ios" || pod repo update --silent
- test "$PLATFORM" != "android" || brew install android && export ANDROID_HOME=$(brew --prefix android)
script:
- fastlane $PLATFORM build
notifications:
  email: false
