osx_image: xcode8
language: objective-c
cache:
  directories:
  - node_modules
  - .ruby-build
branches:
  only:
  - master
  - develop
  - /^feature\/\w+/
env:
  global:
  - RUBY_URL=https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.3.tar.gz
  - BUILD_NUM=$TRAVIS_BUILD_NUMBER
  - PROJECT_REPO_SLUG=$TRAVIS_REPO_SLUG
  - GIT_BRANCH=$TRAVIS_BRANCH
  matrix:
  - PLATFORM=mac
  - PLATFORM=android
  - PLATFORM=ios
before_install:
- rvm use system; ruby -v; type ruby
- test -d .ruby-build/ruby-* || (mkdir .ruby-build; cd .ruby-build; (curl $RUBY_URL | tar zxf -); cd ruby-*; ./configure --with-openssl-dir=$(brew --prefix openssl) --disable-install-doc)
- (cd .ruby-build/ruby-*; make install)
- rvm reset; ruby -v; type ruby
- nvm install 6.9.2
- brew update || brew update
- brew install git-lfs && git-lfs install && git-lfs pull
- git clone https://github.com/fathens/fastlane-ionic.git -b develop fastlane
install:
- gem install fastlane --no-document
- npm install ionic cordova && export PATH="$PATH:$(npm bin)"
- test "$PLATFORM" != "ios" || (gem install cocoapods --no-document && pod repo update --silent)
- test "$PLATFORM" != "android" || (brew install android && export ANDROID_HOME=$(brew --prefix android))
script:
- fastlane $PLATFORM build
notifications:
  email: false
